---
title: "2020_09_15_traceVscales_GoEmo_CaseControl"
author: "Jake Portanova"
date: "September 15, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Individual Trace Score
library(xlsx)
library(dplyr)
library(ggplot2)
library(wordspace)
setwd("C:/Users/jakep/Desktop")
baseline_scales <- read.csv("PORQ_demographicAndBaselineDayData_labeled_scales.csv")
ratings <- read.csv("PORQ_animatedShapes_ratings.csv")
ratings$composite <- ratings$accuracy_rater1 +ratings$accuracy_rater2+ratings$intentionality_rater1+
  ratings$intentionality_rater2
ratings$intentionality <- ratings$intentionality_rater1 + ratings$intentionality_rater2
ratings$accuracy <- ratings$accuracy_rater1 + ratings$accuracy_rater2
ratings$ID <- as.character(ratings[,1])
baseline_scales$ID <- as.character(baseline_scales[,2])
ratings_scales <- inner_join(ratings, baseline_scales, by="ID")
ratings_scales$Case <- as.factor(substr(ratings_scales$ID,1,1))
ratings_scales$condition <- gsub("[0-9.+]", "", ratings_scales$stimulus)
#
library(xlsx)
library(dplyr)
library(ggplot2)
library(wordspace)
setwd("C:/Users/jakep/Dropbox/PORQ_dataForUW/evocativeVideoTask")
evoc_trans <- read.xlsx("PORQ_evocativeVideoTask_transcripts.xlsx", sheetIndex = 1)

# read unbinding
setwd("..")
unblinding <- read.xlsx("PORQ_drugUnblinding.xlsx", sheetIndex = 1)

# IDDay
evoc_trans$IDDay <- paste(evoc_trans$participantID, evoc_trans$day, sep="_")
unblinding$IDDay <- paste(unblinding$participantID, unblinding$day, sep="_")

# Join on ID Day
data <- full_join(unblinding, evoc_trans, by="IDDay")
# replace na's for 8 with pl
data[is.na(data$drugCondition),c("drugCondition")] <- "PL"
# filter for only placebo
data <- data %>% filter(drugCondition == "PL")
# join to go emotions
setwd("C:/Users/jakep/Desktop")
goemo <- read.csv("go_emotions_output.csv")
goemo$Filename <- substr(goemo$file, 17,50) # get filename
goemo$id <- sapply(strsplit(goemo$Filename, "_"), "[", 1)
goemo$emo <- sapply(strsplit(goemo$Filename, "_"), "[", 2)
goemo$thing <- sapply(strsplit(goemo$Filename, "_"), "[", 3)
goemo$Filename <- paste(goemo$id,goemo$emo,goemo$thing, sep="_")
# Create variable for joining
data$Filename <- paste(data$participantID.y,data$stimulus,sep="_")
#data$Filename <- paste(data$Filename,".txt",sep="")

emo_unblind <- right_join(goemo,data,by="Filename")
emo_unblind$Case <- substr(emo_unblind$Filename,1,1)
data2 <- emo_unblind
emo_unblind$emo <- gsub(" neg","neg",emo_unblind$emo)

# Define emotions
#emo_unblind <- emo_unblind %>% group_by(participantID.x) %>% summarise_all(funs(mean))
emo_unblind$positive <- emo_unblind$admiration + emo_unblind$amusement + emo_unblind$approval+
  emo_unblind$caring + emo_unblind$desire + emo_unblind$excitement + emo_unblind$gratitude + emo_unblind$joy +
  emo_unblind$love + emo_unblind$optimism + emo_unblind$pride + emo_unblind$relief

emo_unblind$negative <- emo_unblind$anger + emo_unblind$annoyance + emo_unblind$disappointment +         emo_unblind$disapproval+emo_unblind$disgust+emo_unblind$embarrassment+emo_unblind$fear+emo_unblind$grief+
  emo_unblind$nervousness + emo_unblind$remorse+emo_unblind$sadness

#data4 <- emo_unblind %>% filter(Case == "7")
# (1) average probability across all 1-positive, 2-negative and 3-neutral emotions
data5 <- emo_unblind %>% group_by(id, emo) %>% summarise_all(funs(mean(., na.rm = TRUE)))
data6 <- data5 %>% filter(emo == "joy")
data7 <- data5 %>% filter(emo=="neg")
data67 <- inner_join(data6, data7, by="id")
data8 <- data5 %>% filter(emo == "neu")
data678 <- inner_join(data67, data8, by="id")
data678$trace <- data678$positive.x + data678$negative.y + data678$neutral
data678$Case <- substr(data678$id,1,1)
t.test(data678$trace~data678$Case)

data678 <- data678 %>% rename(ID = id)
ratings_scales$Dose <- ratings_scales$X


scales_trace <- inner_join(data678,ratings_scales, by="ID")

scales_trace <- unique( scales_trace[ , c("ID","Dose","trace","QLS","AMNART","CAINS",                                                                                             
                                           "PANSSpos" ,                                                                                         
                                           "PANSSneg"  ,                                                                                        
                                          "PANSSdisorganization"  ,                                                                            
                                           "RFS"                    ,                                                                           
                                           "Hinting"                 ,                                                                          
                                          "Defeatist"                ,                                                                         
                                           "ECRRSmom"                  ,                                                                        
                                           "ECRRSdad"                   ,                                                                       
                                           "ECRRSromantic"               ,                                                                      
                                          "ECRRSfriend"                  ,                                                                     
                                           "ECRRS",
                                          "Diagnosis..choice.Schizophrenia.",
                                          "Diagnosis..choice.Schizoaffective.Disorder.")]) 
scales_trace$Case <- substr(scales_trace$ID,1,1)

scales_trace[scales_trace$Case == "8",c("PANSSpos")] <- 5
scales_trace[scales_trace$Case == "8",c("PANSSdisorganization")] <- 3
scales_trace[scales_trace$Case == "8",c("Dose")] <- 0
scales_trace$Diagnosis <- NA
scales_trace[scales_trace$Case == "8",c("Diagnosis")] <- "Healthy"
scales_trace[scales_trace$Diagnosis..choice.Schizophrenia.=="Checked",c("Diagnosis")] <- "Schizophrenia"
scales_trace[scales_trace$Diagnosis..choice.Schizoaffective.Disorder.=="Checked",c("Diagnosis")] <- "Schizoaffective"
```
```{r plots, echo=FALSE,warning=FALSE}
ggplot(scales_trace, aes(y=trace,x=CAINS,color=Case))+geom_point(aes(size=Dose, shape=Diagnosis))+geom_smooth(aes(group = Case),method=lm)+ggtitle("Relationship between Negative Symptoms and Trace")+
  ggrepel::geom_text_repel(aes(label = ID), color = "black", size = 2.5, segment.color = "grey")
ggplot(scales_trace, aes(y=trace,x=PANSSpos,color=Case))+geom_point(aes(size=Dose, shape=Diagnosis))+geom_smooth(method=lm)+ggtitle("Relationship between Positive Symptoms and Trace")+
  ggrepel::geom_text_repel(aes(label = ID), color = "black", size = 2.5, segment.color = "grey")
ggplot(scales_trace, aes(y=trace,x=PANSSneg,color=Case))+geom_point(aes(size=Dose, shape=Diagnosis))+geom_smooth(method=lm)+ggtitle("Relationship between Positive Symptoms and Trace")+
  ggrepel::geom_text_repel(aes(label = ID), color = "black", size = 2.5, segment.color = "grey")
ggplot(scales_trace, aes(y=trace,x=PANSSdisorganization,color=Case))+geom_point(aes(size=Dose, shape=Diagnosis))+geom_smooth(method=lm)+ggtitle("Relationship between Disorganization Symptoms and Trace")+
  ggrepel::geom_text_repel(aes(label = ID), color = "black", size = 2.5, segment.color = "grey")
ggplot(scales_trace, aes(y=trace,x=RFS,color=Case))+geom_point(aes(size=Dose, shape=Diagnosis))+geom_smooth(method=lm)+ggtitle("Relationship between Role Functioning and Trace")+
  ggrepel::geom_text_repel(aes(label = ID), color = "black", size = 2.5, segment.color = "grey")
ggplot(scales_trace, aes(y=trace,x=QLS,color=Case))+geom_point(aes(size=Dose, shape=Diagnosis))+geom_smooth(method=lm)+ggtitle("Relationship between Quality of Life and Trace")+
  ggrepel::geom_text_repel(aes(label = ID), color = "black", size = 2.5, segment.color = "grey")
ggplot(scales_trace, aes(y=trace,x=Defeatist,color=Case))+geom_point(aes(size=Dose, shape=Diagnosis))+geom_smooth(method=lm)+ggtitle("Relationship between Defeatist Beliefs and Trace")+
  ggrepel::geom_text_repel(aes(label = ID), color = "black", size = 2.5, segment.color = "grey")
ggplot(scales_trace, aes(y=trace,x=Hinting,color=Case))+geom_point(aes(size=Dose, shape=Diagnosis))+geom_smooth(method=lm)+ggtitle("Relationship between Hinting and Trace")+
  ggrepel::geom_text_repel(aes(label = ID), color = "black", size = 2.5, segment.color = "grey")
ggplot(scales_trace, aes(y=trace,x=ECRRS,color=Case))+geom_point(aes(size=Dose, shape=Diagnosis))+geom_smooth(method=lm)+ggtitle("Relationship between ECRRS and Trace")+
  ggrepel::geom_text_repel(aes(label = ID), color = "black", size = 2.5, segment.color = "grey")
ggplot(scales_trace, aes(y=trace,x=AMNART,color=Case))+geom_point(aes(size=Dose, shape=Diagnosis))+geom_smooth(method=lm)+ggtitle("Relationship between AMNART and Trace")+
  ggrepel::geom_text_repel(aes(label = ID), color = "black", size = 2.5, segment.color = "grey")
ggplot(scales_trace, aes(y=trace,x=ECRRSmom,color=Case))+geom_point(aes(size=Dose, shape=Diagnosis))+geom_smooth(method=lm)+ggtitle("Relationship between Positive Symptoms and Trace")
ggplot(scales_trace, aes(y=trace,x=ECRRSdad,color=Case))+geom_point(aes(size=Dose, shape=Diagnosis))+geom_smooth(method=lm)+ggtitle("Relationship between Positive Symptoms and Trace")
ggplot(scales_trace, aes(y=trace,x=ECRRSromantic,color=Case))+geom_point(aes(size=Dose, shape=Diagnosis))+geom_smooth(method=lm)+ggtitle("Relationship between Positive Symptoms and Trace")
ggplot(scales_trace, aes(y=trace,x=ECRRSfriend,color=Case))+geom_point()+geom_smooth(method=lm)+ggtitle("Relationship between Positive Symptoms and Trace")
cor(scales_trace[,c("trace","QLS","AMNART","CAINS",                                                                                             
                                           "PANSSpos" ,                                                                                         
                                           "PANSSneg"  ,                                                                                        
                                          "PANSSdisorganization"  ,                                                                            
                                           "RFS"                    ,                                                                           
                                           "Hinting"                 ,                                                                          
                                          "Defeatist"                ,                                                                         
                                           "ECRRSmom"                  ,                                                                        
                                           "ECRRSdad"                   ,                                                                       
                                           "ECRRSromantic"               ,                                                                      
                                          "ECRRSfriend"                  ,                                                                     
                                           "ECRRS")], use="complete.obs")
```

