---
title: "2020_08_16_evoc_CaseVControl_LIWC"
author: "Jake Portanova"
date: "August 16, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xlsx)
library(dplyr)
library(ggplot2)
setwd("C:/Users/jakep/Dropbox/PORQ_dataForUW/evocativeVideoTask")
evoc_trans <- read.xlsx("PORQ_evocativeVideoTask_transcripts.xlsx", sheetIndex = 1)

# read unbinding
setwd("..")
unblinding <- read.xlsx("PORQ_drugUnblinding.xlsx", sheetIndex = 1)

# IDDay
evoc_trans$IDDay <- paste(evoc_trans$participantID, evoc_trans$day, sep="_")
unblinding$IDDay <- paste(unblinding$participantID, unblinding$day, sep="_")

# Join on ID Day
data <- full_join(unblinding, evoc_trans, by="IDDay")
# replace na's for 8 with pl
data[is.na(data$drugCondition),c("drugCondition")] <- "PL"
# filter for only placebo
data <- data %>% filter(drugCondition == "PL")
# data <- data %>% filter(drugCondition == "OT")

# set wd
setwd("evocativeVideoTask")
# read in liwc
evoc <- read.csv("LIWC2015 Results (emotextfiles (1732 files)).csv")
evoc$Filename <- as.character(evoc$Filename)
evoc$id <- sapply(strsplit(evoc$Filename, "_"), "[", 1)
evoc$emo <- sapply(strsplit(evoc$Filename, "_"), "[", 2)
evoc$thing <- sapply(strsplit(evoc$Filename, "_"), "[", 3)
evoc$IDstimulus <- paste(evoc$id,evoc$emo,evoc$thing, sep="_")

data$IDstimulus <- paste(data$participantID.y,data$stimulus, sep="_")
data2 <- data
# make id stimulus variable
data3 <- right_join(data2, evoc, by="IDstimulus")
# merge liwc with 
data3$Case <- substr(data3$participantID.y,1,1)
```

```{r output}
data4 <- data3 %>% group_by(Case) %>% summarise_all(funs(mean(., na.rm = TRUE)))
a <- data.frame()
for(i in 17:109){
  var1 <- colnames(data3)[i]
  t <- t.test(data3[,var1]~data3$Case, alternative = "two.sided")
  a[i-16,c('p_value')] <- t$p.value
  var <- colnames(data3)[i]
  a[i-16,c('var')] <- colnames(data3)[i]
  a[i-16, c('Cases')] <- data4[1,var]
  a[i-16,c("Controls")] <- data4[2,var]
  #   library(broom)
  #   library(dplyr)
  # a <- liwc %>% group_by(Status) %>% do(tidy(t.test(liwc[i])))
}
attach(a)
# sort by p
newdata <- a[order(p_value),]
detach(a)
newdata$p_value <- round(newdata$p_value, digits=3)
newdata$Cases <- round(newdata$Cases, digits=3)
newdata$Controls <- round(newdata$Controls, digits=3)
print(na.omit(newdata))
# View(na.omit(newdata))

#data <- order(data$p.value) 
#print(data)
#newdata <- newdata[1:91,]
for(i in 17:109){
  var1 <- newdata$var[i-16]
  print(ggplot(data3, aes_string(x='Case', y=data3[,newdata$var[i-16]], fill='Case',group='Case'))+geom_boxplot()+ggtitle(newdata$var[i-16]))
#  print(t.test(data3[,var1]~data3$Case))
}
```

```{r pos}
data3$condition <- substr(data3$stimulus,1,3)
#data4 <- data3 %>% filter(condition == "joy")
data4 <- data3 %>% group_by(Case) %>% summarise_all(funs(mean(., na.rm = TRUE)))
a <- data.frame()
for(i in 17:109){
  var1 <- colnames(data3)[i]
  t <- t.test(data3[,var1]~data3$Case, alternative = "two.sided")
  a[i-16,c('p_value')] <- t$p.value
  var <- colnames(data3)[i]
  a[i-16,c('var')] <- colnames(data3)[i]
  a[i-16, c('Cases')] <- data4[1,var]
  a[i-16,c("Controls")] <- data4[2,var]
  #   library(broom)
  #   library(dplyr)
  # a <- liwc %>% group_by(Status) %>% do(tidy(t.test(liwc[i])))
}
attach(a)
# sort by p
newdata <- a[order(p_value),]
detach(a)
newdata$p_value <- round(newdata$p_value, digits=3)
newdata$Cases <- round(newdata$Cases, digits=3)
newdata$Controls <- round(newdata$Controls, digits=3)
print(na.omit(newdata))
# View(na.omit(newdata))

#data <- order(data$p.value) 
#print(data)
#newdata <- newdata[1:91,]
for(i in 17:109){
  var1 <- newdata$var[i-16]
  print(ggplot(data3, aes_string(x='Case', y=data3[,newdata$var[i-16]], fill='Case',group='Case'))+geom_boxplot()+ggtitle(newdata$var[i-16]))
#  print(t.test(data3[,var1]~data3$Case))
}
```

```{r}
data4 <- data3[grep("joy",data3$Filename),]
data_case <- data4 %>% filter(Case == 7)
data_case <- data_case %>% group_by(participantID.x) %>% summarise_all(funs(mean(., na.rm = TRUE)))
data_case$positive <- data_case$posemo
data_case$negative <- data_case$negemo
data_case$neutral <- 100 - data_case$posemo - data_case$negemo
mean(data_case$positive, na.rm=TRUE)
mean(data_case$negative, na.rm=TRUE)


data4 <- data3[grep("joy",data3$Filename),]
data_control <- data4 %>% filter(Case == 8)
data_control <- data_control %>% group_by(participantID.y) %>% summarise_all(funs(mean(., na.rm = TRUE)))
data_control$positive <- data_control$posemo

data_control$negative <- data_control$negemo
data_control$neutral <- 100 - data_control$posemo - data_control$negemo

mean(data_control$positive, na.rm = TRUE)
mean(data_control$negative, na.rm = TRUE)


liwcp <- data.frame()
t1 <- t.test(data_case$positive, data_control$positive)
t2 <- t.test(data_case$negative, data_control$negative)
t3 <- t.test(data_case$neutral, data_control$neutral)
liwcp[c("joy"),c("posemo")] <- t1$p.value
liwcp[c("joy"),c("negemo")] <- t2$p.value
liwcp[c("joy"),c("neuemo")] <- t3$p.value
```

```{r}
data4 <- data3[grep("neg",data3$Filename),]
data_case <- data4 %>% filter(Case == 7)
data_case <- data_case %>% group_by(participantID.y) %>% summarise_all(funs(mean(., na.rm = TRUE)))
data_case$positive <- data_case$posemo

data_case$negative <- data_case$negemo
data_case$neutral <- 100 - data_case$posemo - data_case$negemo
mean(data_case$positive, na.rm=TRUE)
mean(data_case$negative, na.rm=TRUE)
mean(data_case$neutral, na.rm=TRUE)

data4 <- data3[grep("neg",data3$Filename),]
data_control <- data4 %>% filter(Case == 8)
data_control <- data_control %>% group_by(participantID.y) %>% summarise_all(funs(mean(., na.rm = TRUE)))
data_control$positive <- data_control$posemo

data_control$negative <- data_control$negemo
data_control$neutral <- 100 - data_control$posemo - data_control$negemo
mean(data_control$positive, na.rm = TRUE)
mean(data_control$negative, na.rm = TRUE)
mean(data_control$neutral, na.rm=TRUE)


t1 <- t.test(data_case$positive, data_control$positive)
t2 <- t.test(data_case$negative, data_control$negative)
t3 <- t.test(data_case$neutral, data_control$neutral)
liwcp[c("neg"),c("posemo")] <- t1$p.value
liwcp[c("neg"),c("negemo")] <- t2$p.value
liwcp[c("neg"),c("neuemo")] <- t3$p.value

```

```{r}
data4 <- data3[grep("neu",data3$Filename),]
data_case <- data4 %>% filter(Case == 7)
data_case <- data_case %>% group_by(participantID.y) %>% summarise_all(funs(mean(., na.rm = TRUE)))
data_case$positive <- data_case$posemo
data_case$negative <- data_case$negemo

data_case$neutral <- 100 - data_case$posemo - data_case$negemo

mean(data_case$positive, na.rm=TRUE)
mean(data_case$negative, na.rm=TRUE)


data4 <- data3[grep("neu",data3$Filename),]
data_control <- data4 %>% filter(Case == 8)
data_control <- data_control %>% group_by(participantID.y) %>% summarise_all(funs(mean(., na.rm = TRUE)))
data_control$positive <- data_control$posemo
data_control$negative <- data_control$negemo

data_control$neutral <- 100 - data_control$posemo - data_control$negemo

mean(data_control$positive, na.rm = TRUE)
mean(data_control$negative, na.rm = TRUE)
t1 <- t.test(data_case$positive, data_control$positive)
t2 <- t.test(data_case$negative, data_control$negative)
t3 <- t.test(data_case$neutral, data_control$neutral)
liwcp[c("neu"),c("posemo")] <- t1$p.value
liwcp[c("neu"),c("negemo")] <- t2$p.value
liwcp[c("neu"),c("neuemo")] <- t3$p.value



```