---
title: "2020_10_21_AnalysisOfTrace"
author: "Jake Portanova"
date: "October 21, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xlsx)
library(dplyr)
library(ggplot2)
library(wordspace)
library(ROCR)
setwd("C:/Users/jakep/Dropbox/PORQ_dataForUW/evocativeVideoTask")
evoc_trans <- read.xlsx("PORQ_evocativeVideoTask_transcripts.xlsx", sheetIndex = 1)

# read unbinding
setwd("..")
unblinding <- read.xlsx("PORQ_drugUnblinding.xlsx", sheetIndex = 1)

# IDDay
evoc_trans$IDDay <- paste(evoc_trans$participantID, evoc_trans$day, sep="_")
unblinding$IDDay <- paste(unblinding$participantID, unblinding$day, sep="_")

# Join on ID Day
data <- full_join(unblinding, evoc_trans, by="IDDay")
# replace na's for 8 with pl
data[is.na(data$drugCondition),c("drugCondition")] <- "PL"
# filter for only placebo
data <- data %>% filter(drugCondition == "PL")
# join to go emotions
setwd("C:/Users/jakep/Desktop")
goemo <- read.csv("go_emotions_output.csv")
goemo$Filename <- substr(goemo$file, 17,50) # get filename
goemo$id <- sapply(strsplit(goemo$Filename, "_"), "[", 1)
goemo$emo <- sapply(strsplit(goemo$Filename, "_"), "[", 2)
goemo$thing <- sapply(strsplit(goemo$Filename, "_"), "[", 3)
goemo$feeldescribe <- sapply(strsplit(goemo$Filename, "_"), "[", 4)
goemo <- goemo[grep("feel",goemo$feeldescribe),]
goemo$Filename <- paste(goemo$id,goemo$emo,goemo$thing, sep="_")
# Create variable for joining
data$Filename <- paste(data$participantID.y,data$stimulus,sep="_")
#data$Filename <- paste(data$Filename,".txt",sep="")

emo_unblind <- right_join(goemo,data,by="Filename")
emo_unblind$Case <- substr(emo_unblind$Filename,1,1)
data2 <- emo_unblind

# Define emotions
#emo_unblind <- emo_unblind %>% group_by(participantID.x) %>% summarise_all(funs(mean))
emo_unblind$positive <- (emo_unblind$admiration + emo_unblind$amusement + emo_unblind$approval+
                           emo_unblind$caring + emo_unblind$desire + emo_unblind$excitement + emo_unblind$gratitude + emo_unblind$joy +
                           emo_unblind$love + emo_unblind$optimism + emo_unblind$pride + emo_unblind$relief)/12

emo_unblind$negative <- (emo_unblind$anger + emo_unblind$annoyance + emo_unblind$disappointment +         
                           emo_unblind$disapproval+emo_unblind$disgust+emo_unblind$embarrassment+
                           emo_unblind$fear+emo_unblind$grief+emo_unblind$nervousness +
                           emo_unblind$remorse+emo_unblind$sadness)/11

emo_unblind2 <- emo_unblind[,c("positive","negative")]
emo_unblind <- emo_unblind[ , -which(names(emo_unblind) %in% c("positive","negative","neutral"))]
emo_unblind2 <- normalize.rows(as.matrix(emo_unblind2),method="manhattan")
emo_unblind_norm <- cbind(emo_unblind,emo_unblind2)
emo_unblind_norm[,"pos_max"] <- apply(emo_unblind_norm[,c("admiration", "amusement","approval",
                           "caring", "desire", "excitement", "gratitude", 
                           "joy", "love","optimism", "pride", "relief")],1,max)
emo_unblind_norm[,"neg_max"] <- apply(emo_unblind_norm[,c("anger", "annoyance", "disappointment", "disapproval","disgust","embarrassment","fear","grief","nervousness", "remorse","sadness")],1,max)
data5 <- emo_unblind_norm %>% group_by(id, emo) %>% summarise_all(funs(mean(., na.rm = TRUE)))
```

```{r}
#data4 <- emo_unblind_norm %>% filter(Case == "7")
# (1) average probability across all 1-positive, 2-negative and 3-neutral emotions
data5$Case <- as.factor(substr(data5$id,1,1))
data_joy <- data5 %>% filter(emo == "joy")
t.test(positive~Case, data=data_joy)
```

```{r}
data6 <- data5 %>% filter(emo == "joy")
data6_r <- data6[,c("positive","negative")]
data6_r <- normalize.rows(as.matrix(data6_r),method="manhattan")
data6 <- data6[ , -which(names(data6) %in% c("positive","negative"))]
data6_r <- as.data.frame(data6_r)
data6_r2 <- cbind(data6,data6_r)
t.test(positive~Case, data=data6_r2)
```

```{r max}
data6 <- data5 %>% filter(emo == "joy")
# data6[,"pos_max"] <- apply(data6[,c("admiration", "amusement","approval",
#                            "caring", "desire", "excitement", "gratitude",
#                            "joy", "love","optimism", "pride", "relief")],1,max)
# data6[,"neg_max"] <- apply(data6[,c("anger", "annoyance", "disappointment", "disapproval","disgust","embarrassment","fear","grief","nervousness", "remorse","sadness")],1,max)
data6_r <- data6[,c("pos_max","neg_max")]
data6_r <- normalize.rows(as.matrix(data6_r),method="manhattan")
data6 <- data6[ , -which(names(data6) %in% c("pos_max","neg_max"))]
data6_r <- as.data.frame(data6_r)
data6_r2 <- cbind(data6,data6_r)
t.test(pos_max~Case, data=data6_r2)
```

```{r}
set.seed(2)
samp <- sample(c(1:88), size=71, replace=FALSE)
train <- data_joy[samp,]
test <- data_joy[-samp,]
glm <- glm(Case~positive,data=train,family=binomial())
test_prob = predict(glm, newdata = test, type = "response")
pred <- prediction( test_prob, test$Case )
perf <- performance( pred, "tpr", "fpr" )
text = performance(pred, "auc")@y.values
plot( perf, col="red")
text(1,0.25,labels=paste("AUC =",text,sep=" "))
```

```{r}
set.seed(2)
samp <- sample(c(1:88), size=71, replace=FALSE)
train <- data6_r2[samp,]
test <- data6_r2[-samp,]
glm <- glm(Case~pos_max,data=data6_r2,family=binomial())
test_prob = predict(glm, newdata = data6_r2, type = "response")
pred <- prediction( data6_r2$pos_max, data6_r2$Case )
perf <- performance( pred, "tpr", "fpr" )
text = performance(pred, "auc")@y.values
plot( perf, col="red")
text(.5,0.25,labels=paste("AUC =",text,sep=" "))
```

```{r}
data6 <- data5 %>% filter(emo == "joy")
data7 <- data5 %>% filter(emo=="neg")
data67 <- inner_join(data6, data7, by="id")
data8 <- data5 %>% filter(emo == "neu")
data678 <- inner_join(data67, data8, by="id")
data678$trace <- data678$positive.x + data678$negative.y 
t.test(trace~Case, data=data678)
```

```{r}
set.seed(2)
samp <- sample(c(1:88), size=71, replace=FALSE)
train <- data678[samp,]
test <- data678[-samp,]
glm <- glm(Case~trace,data=train,family=binomial())
test_prob = predict(glm, newdata = test, type = "response")
pred <- prediction( test_prob, test$Case )
perf <- performance( pred, "tpr", "fpr" )
text = performance(pred, "auc")@y.values
plot( perf, col="red")
text(1,0.25,labels=paste("AUC =",text,sep=" "))
```

```{r}
data6 <- data5 %>% filter(emo == "joy")
data6_r <- data6[,c("positive","negative")]
data6_r <- normalize.rows(as.matrix(data6_r),method="manhattan")
data6 <- data6[ , -which(names(data6) %in% c("positive","negative"))]
data6_r <- as.data.frame(data6_r)
data6_r2 <- cbind(data6,data6_r)
data7 <- data5 %>% filter(emo=="neg")
data7_r <- data7[,c("positive","negative")]
data7_r <- normalize.rows(as.matrix(data7_r),method="manhattan")
data7 <- data7[ , -which(names(data7) %in% c("positive","negative"))]
data7_r <- as.data.frame(data7_r)
data7_r2 <- cbind(data7,data7_r)
data67 <- inner_join(data6_r2, data7_r2, by="id")
data8 <- data5 %>% filter(emo == "neu")
data678 <- inner_join(data67, data8, by="id")
data678$trace <- data678$positive.x + data678$negative.y 
t.test(trace~Case, data=data678)
```

```{r}
set.seed(2)
samp <- sample(c(1:88), size=71, replace=FALSE)
train <- data678[samp,]
test <- data678[-samp,]
glm <- glm(Case~trace,data=train,family=binomial())
test_prob = predict(glm, newdata = test, type = "response")
pred <- prediction( test_prob, test$Case )
perf <- performance( pred, "tpr", "fpr" )
text = performance(pred, "auc")@y.values
plot( perf, col="red")
text(1,0.25,labels=paste("AUC =",text,sep=" "))
```

```{r}
data6 <- data5 %>% filter(emo == "joy")
# data6[,"pos_max"] <- apply(data6[,c("admiration", "amusement","approval",
#                            "caring", "desire", "excitement", "gratitude",
#                            "joy", "love","optimism", "pride", "relief")],1,max)
# data6[,"neg_max"] <- apply(data6[,c("anger", "annoyance", "disappointment", "disapproval","disgust","embarrassment","fear","grief","nervousness", "remorse","sadness")],1,max)
data6_r <- data6[,c("pos_max","neg_max")]
data6_r <- normalize.rows(as.matrix(data6_r),method="manhattan")
data6 <- data6[ , -which(names(data6) %in% c("pos_max","neg_max"))]
data6_r <- as.data.frame(data6_r)
data6_r2 <- cbind(data6,data6_r)

data7 <- data5 %>% filter(emo=="neg")
# data7[,"pos_max"] <- apply(data7[,c("admiration", "amusement","approval",
#                            "caring", "desire", "excitement", "gratitude", 
#                            "joy", "love","optimism", "pride", "relief")],1,max)
# data7[,"neg_max"] <- apply(data7[,c("anger", "annoyance", "disappointment", "disapproval","disgust","embarrassment","fear","grief","nervousness", "remorse","sadness")],1,max)
data7_r <- data7[,c("pos_max","neg_max")]
data7_r <- normalize.rows(as.matrix(data7_r),method="manhattan")
data7 <- data7[ , -which(names(data7) %in% c("pos_max","neg_max"))]
data7_r <- as.data.frame(data7_r)
data7_r2 <- cbind(data7,data7_r)

data67 <- inner_join(data6_r2, data7_r2, by="id")
data8 <- data5 %>% filter(emo == "neu")
data678 <- inner_join(data67, data8, by="id")
data678$trace <- data678$pos_max.x + data678$neg_max.y 
t.test(trace~Case, data=data678)
```

```{r}
set.seed(2)
samp <- sample(c(1:88), size=71, replace=FALSE)
train <- data678[samp,]
test <- data678[-samp,]
glm <- glm(Case~trace,data=train,family=binomial())
test_prob = predict(glm, newdata = test, type = "response")
pred <- prediction( test_prob, test$Case )
perf <- performance( pred, "tpr", "fpr" )
text = performance(pred, "auc")@y.values
plot( perf, col="red")
text(1,0.25,labels=paste("AUC =",text,sep=" "))
```

```{r}
pred <- prediction( data678$trace, data678$Case )
perf <- performance( pred, "tpr", "fpr" )
text = performance(pred, "auc")@y.values
plot( perf, col="red")
text(1,0.25,labels=paste("AUC =",text,sep=" "))
```

